// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "rezofin-backend-api",
    "version": "1"
  },
  "paths": {
    "/get-user": {
      "get": {
        "summary": "getUser",
        "description": "",
        "operationId": "getUser.get./get-user",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/create-user-data": {
      "post": {
        "summary": "createUser",
        "description": "",
        "operationId": "createUser.post./create-user-data",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/get-user-data-byId/{ID}": {
      "get": {
        "summary": "getUserById",
        "description": "",
        "operationId": "getUserById.get./get-user-data-byId/{ID}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "ID",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/update-user-data-byId/{ID}": {
      "put": {
        "summary": "updateUserById",
        "description": "",
        "operationId": "updateUserById.put./update-user-data-byId/{ID}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "ID",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/delete-user-data-byId/{ID}": {
      "delete": {
        "summary": "deleteUserById",
        "description": "",
        "operationId": "deleteUserById.delete./delete-user-data-byId/{ID}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "ID",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};